name: ci

on: [push, pull_request]

jobs:

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.10','3.11','3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.18"
          python-version: ${{ matrix.python-version }}

  #     - name: Report coverage to Coveralls
  #       uses: coverallsapp/github-action@v2
  #       with:
  #         parallel: true
  #         flag-name: run-${{ matrix.python-version }}
  #         file: coverage.xml
  #         base-path: api

  # coverage:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Close parallel build
  #       uses: coverallsapp/github-action@v2
  #       with:
  #         parallel-finished: true

  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.18"
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync

      - name: Run pre-commit
        run: |
          uv run pre-commit install
          uv run pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
